nohup: ignoring input
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'hvac', 'dr', 'dw', 'mw']
Round: 500 Training Error: tensor(540.7488, device='cuda:0') Validation Error: tensor(494.5937, device='cuda:0') Test Error: tensor(603.1588, device='cuda:0')
Round: 1000 Training Error: tensor(421.1682, device='cuda:0') Validation Error: tensor(379.6960, device='cuda:0') Test Error: tensor(474.8854, device='cuda:0')
Round: 1500 Training Error: tensor(310.6996, device='cuda:0') Validation Error: tensor(278.6307, device='cuda:0') Test Error: tensor(364.5366, device='cuda:0')
Round: 2000 Training Error: tensor(262.9566, device='cuda:0') Validation Error: tensor(248.8638, device='cuda:0') Test Error: tensor(328.4739, device='cuda:0')
Round: 2500 Training Error: tensor(253.3811, device='cuda:0') Validation Error: tensor(247.3106, device='cuda:0') Test Error: tensor(319.5363, device='cuda:0')
Round: 3000 Training Error: tensor(250.7897, device='cuda:0') Validation Error: tensor(247.8036, device='cuda:0') Test Error: tensor(316.9188, device='cuda:0')
Round: 3500 Training Error: tensor(248.6979, device='cuda:0') Validation Error: tensor(254.5592, device='cuda:0') Test Error: tensor(316.0587, device='cuda:0')
Round: 4000 Training Error: tensor(247.2954, device='cuda:0') Validation Error: tensor(254.8028, device='cuda:0') Test Error: tensor(315.7237, device='cuda:0')
Round: 4500 Training Error: tensor(245.4683, device='cuda:0') Validation Error: tensor(254.7841, device='cuda:0') Test Error: tensor(314.3885, device='cuda:0')
Round: 5000 Training Error: tensor(241.7926, device='cuda:0') Validation Error: tensor(251.6735, device='cuda:0') Test Error: tensor(312.3117, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'hvac', 'dr', 'mw', 'dw']
Round: 500 Training Error: tensor(540.9296, device='cuda:0') Validation Error: tensor(494.8006, device='cuda:0') Test Error: tensor(603.5096, device='cuda:0')
Round: 1000 Training Error: tensor(421.0946, device='cuda:0') Validation Error: tensor(378.0170, device='cuda:0') Test Error: tensor(475.1588, device='cuda:0')
Round: 1500 Training Error: tensor(310.8360, device='cuda:0') Validation Error: tensor(275.5541, device='cuda:0') Test Error: tensor(365.7365, device='cuda:0')
Round: 2000 Training Error: tensor(262.5820, device='cuda:0') Validation Error: tensor(252.2649, device='cuda:0') Test Error: tensor(327.5467, device='cuda:0')
Round: 2500 Training Error: tensor(253.4399, device='cuda:0') Validation Error: tensor(252.4379, device='cuda:0') Test Error: tensor(318.7285, device='cuda:0')
Round: 3000 Training Error: tensor(250.9261, device='cuda:0') Validation Error: tensor(253.9801, device='cuda:0') Test Error: tensor(316.4654, device='cuda:0')
Round: 3500 Training Error: tensor(249.4919, device='cuda:0') Validation Error: tensor(258.8363, device='cuda:0') Test Error: tensor(317.7111, device='cuda:0')
Round: 4000 Training Error: tensor(247.5783, device='cuda:0') Validation Error: tensor(258.0035, device='cuda:0') Test Error: tensor(316.2471, device='cuda:0')
Round: 4500 Training Error: tensor(245.3498, device='cuda:0') Validation Error: tensor(256.4058, device='cuda:0') Test Error: tensor(313.8629, device='cuda:0')
Round: 5000 Training Error: tensor(241.6535, device='cuda:0') Validation Error: tensor(254.4003, device='cuda:0') Test Error: tensor(311.4521, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'hvac', 'dw', 'dr', 'mw']
Round: 500 Training Error: tensor(540.4772, device='cuda:0') Validation Error: tensor(494.5644, device='cuda:0') Test Error: tensor(603.2224, device='cuda:0')
Round: 1000 Training Error: tensor(421.0853, device='cuda:0') Validation Error: tensor(378.3482, device='cuda:0') Test Error: tensor(475.2293, device='cuda:0')
Round: 1500 Training Error: tensor(310.8496, device='cuda:0') Validation Error: tensor(273.9450, device='cuda:0') Test Error: tensor(364.1911, device='cuda:0')
Round: 2000 Training Error: tensor(261.7652, device='cuda:0') Validation Error: tensor(249.7842, device='cuda:0') Test Error: tensor(327.6754, device='cuda:0')
Round: 2500 Training Error: tensor(252.8114, device='cuda:0') Validation Error: tensor(248.5434, device='cuda:0') Test Error: tensor(318.8609, device='cuda:0')
Round: 3000 Training Error: tensor(250.0901, device='cuda:0') Validation Error: tensor(252.8839, device='cuda:0') Test Error: tensor(317.2354, device='cuda:0')
Round: 3500 Training Error: tensor(248.8185, device='cuda:0') Validation Error: tensor(256.0631, device='cuda:0') Test Error: tensor(316.4859, device='cuda:0')
Round: 4000 Training Error: tensor(247.5928, device='cuda:0') Validation Error: tensor(254.9688, device='cuda:0') Test Error: tensor(315.1756, device='cuda:0')
Round: 4500 Training Error: tensor(245.7898, device='cuda:0') Validation Error: tensor(257.4465, device='cuda:0') Test Error: tensor(311.6621, device='cuda:0')
Round: 5000 Training Error: tensor(241.7233, device='cuda:0') Validation Error: tensor(254.4645, device='cuda:0') Test Error: tensor(311.7406, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'hvac', 'dw', 'mw', 'dr']
Round: 500 Training Error: tensor(540.5177, device='cuda:0') Validation Error: tensor(494.2285, device='cuda:0') Test Error: tensor(602.9045, device='cuda:0')
Round: 1000 Training Error: tensor(421.1093, device='cuda:0') Validation Error: tensor(377.4862, device='cuda:0') Test Error: tensor(474.8293, device='cuda:0')
Round: 1500 Training Error: tensor(311.6749, device='cuda:0') Validation Error: tensor(271.2267, device='cuda:0') Test Error: tensor(362.1357, device='cuda:0')
Round: 2000 Training Error: tensor(262.6438, device='cuda:0') Validation Error: tensor(248.6483, device='cuda:0') Test Error: tensor(324.5872, device='cuda:0')
Round: 2500 Training Error: tensor(252.5118, device='cuda:0') Validation Error: tensor(251.9520, device='cuda:0') Test Error: tensor(315.9664, device='cuda:0')
Round: 3000 Training Error: tensor(250.1609, device='cuda:0') Validation Error: tensor(255.6249, device='cuda:0') Test Error: tensor(316.2849, device='cuda:0')
Round: 3500 Training Error: tensor(249.4343, device='cuda:0') Validation Error: tensor(256.1884, device='cuda:0') Test Error: tensor(316.7776, device='cuda:0')
Round: 4000 Training Error: tensor(248.1342, device='cuda:0') Validation Error: tensor(259.6021, device='cuda:0') Test Error: tensor(315.2752, device='cuda:0')
Round: 4500 Training Error: tensor(246.3478, device='cuda:0') Validation Error: tensor(258.2045, device='cuda:0') Test Error: tensor(314.3584, device='cuda:0')
Round: 5000 Training Error: tensor(243.1282, device='cuda:0') Validation Error: tensor(253.0277, device='cuda:0') Test Error: tensor(312.2636, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'hvac', 'mw', 'dr', 'dw']
Round: 500 Training Error: tensor(541.7664, device='cuda:0') Validation Error: tensor(495.9327, device='cuda:0') Test Error: tensor(604.6755, device='cuda:0')
Round: 1000 Training Error: tensor(421.6470, device='cuda:0') Validation Error: tensor(378.3382, device='cuda:0') Test Error: tensor(474.8247, device='cuda:0')
Round: 1500 Training Error: tensor(311.6115, device='cuda:0') Validation Error: tensor(274.9486, device='cuda:0') Test Error: tensor(365.1414, device='cuda:0')
Round: 2000 Training Error: tensor(263.8468, device='cuda:0') Validation Error: tensor(249.4677, device='cuda:0') Test Error: tensor(325.0050, device='cuda:0')
Round: 2500 Training Error: tensor(254.4868, device='cuda:0') Validation Error: tensor(246.9393, device='cuda:0') Test Error: tensor(316.3777, device='cuda:0')
Round: 3000 Training Error: tensor(251.8163, device='cuda:0') Validation Error: tensor(250.7705, device='cuda:0') Test Error: tensor(315.9841, device='cuda:0')
Round: 3500 Training Error: tensor(250.5256, device='cuda:0') Validation Error: tensor(252.4687, device='cuda:0') Test Error: tensor(316.0430, device='cuda:0')
Round: 4000 Training Error: tensor(249.2583, device='cuda:0') Validation Error: tensor(252.8862, device='cuda:0') Test Error: tensor(315.2609, device='cuda:0')
Round: 4500 Training Error: tensor(247.3918, device='cuda:0') Validation Error: tensor(252.6938, device='cuda:0') Test Error: tensor(313.7212, device='cuda:0')
Round: 5000 Training Error: tensor(243.3816, device='cuda:0') Validation Error: tensor(333.6700, device='cuda:0') Test Error: tensor(309.9816, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'hvac', 'mw', 'dw', 'dr']
Round: 500 Training Error: tensor(540.8680, device='cuda:0') Validation Error: tensor(494.8062, device='cuda:0') Test Error: tensor(603.4875, device='cuda:0')
Round: 1000 Training Error: tensor(421.2466, device='cuda:0') Validation Error: tensor(378.1595, device='cuda:0') Test Error: tensor(474.7172, device='cuda:0')
Round: 1500 Training Error: tensor(310.6274, device='cuda:0') Validation Error: tensor(276.6338, device='cuda:0') Test Error: tensor(365.2109, device='cuda:0')
Round: 2000 Training Error: tensor(263.6131, device='cuda:0') Validation Error: tensor(251.6564, device='cuda:0') Test Error: tensor(329.7806, device='cuda:0')
Round: 2500 Training Error: tensor(253.8825, device='cuda:0') Validation Error: tensor(251.1723, device='cuda:0') Test Error: tensor(320.6145, device='cuda:0')
Round: 3000 Training Error: tensor(251.2240, device='cuda:0') Validation Error: tensor(252.7844, device='cuda:0') Test Error: tensor(319.3903, device='cuda:0')
Round: 3500 Training Error: tensor(249.9784, device='cuda:0') Validation Error: tensor(255.8364, device='cuda:0') Test Error: tensor(319.0105, device='cuda:0')
Round: 4000 Training Error: tensor(248.6733, device='cuda:0') Validation Error: tensor(257.2830, device='cuda:0') Test Error: tensor(318.5076, device='cuda:0')
Round: 4500 Training Error: tensor(246.7314, device='cuda:0') Validation Error: tensor(261.2389, device='cuda:0') Test Error: tensor(317.7490, device='cuda:0')
Round: 5000 Training Error: tensor(242.6032, device='cuda:0') Validation Error: tensor(259.7669, device='cuda:0') Test Error: tensor(315.1324, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dr', 'hvac', 'dw', 'mw']
Round: 500 Training Error: tensor(540.4761, device='cuda:0') Validation Error: tensor(494.5511, device='cuda:0') Test Error: tensor(603.3027, device='cuda:0')
Round: 1000 Training Error: tensor(420.9687, device='cuda:0') Validation Error: tensor(378.2229, device='cuda:0') Test Error: tensor(475.6812, device='cuda:0')
Round: 1500 Training Error: tensor(309.7191, device='cuda:0') Validation Error: tensor(273.7128, device='cuda:0') Test Error: tensor(366.0828, device='cuda:0')
Round: 2000 Training Error: tensor(261.0496, device='cuda:0') Validation Error: tensor(249.7158, device='cuda:0') Test Error: tensor(323.5958, device='cuda:0')
Round: 2500 Training Error: tensor(250.9980, device='cuda:0') Validation Error: tensor(250.5454, device='cuda:0') Test Error: tensor(316.6098, device='cuda:0')
Round: 3000 Training Error: tensor(246.8960, device='cuda:0') Validation Error: tensor(257.3259, device='cuda:0') Test Error: tensor(317.6801, device='cuda:0')
Round: 3500 Training Error: tensor(245.0422, device='cuda:0') Validation Error: tensor(259.3013, device='cuda:0') Test Error: tensor(319.3596, device='cuda:0')
Round: 4000 Training Error: tensor(244.2634, device='cuda:0') Validation Error: tensor(259.9285, device='cuda:0') Test Error: tensor(322.6207, device='cuda:0')
Round: 4500 Training Error: tensor(242.7516, device='cuda:0') Validation Error: tensor(261.2322, device='cuda:0') Test Error: tensor(322.4071, device='cuda:0')
Round: 5000 Training Error: tensor(240.7559, device='cuda:0') Validation Error: tensor(260.3434, device='cuda:0') Test Error: tensor(321.6270, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dr', 'hvac', 'mw', 'dw']
Round: 500 Training Error: tensor(540.5131, device='cuda:0') Validation Error: tensor(494.3383, device='cuda:0') Test Error: tensor(603.2975, device='cuda:0')
Round: 1000 Training Error: tensor(420.9727, device='cuda:0') Validation Error: tensor(378.2314, device='cuda:0') Test Error: tensor(475.8162, device='cuda:0')
Round: 1500 Training Error: tensor(309.9053, device='cuda:0') Validation Error: tensor(272.3615, device='cuda:0') Test Error: tensor(365.9858, device='cuda:0')
Round: 2000 Training Error: tensor(261.9679, device='cuda:0') Validation Error: tensor(244.1738, device='cuda:0') Test Error: tensor(326.0763, device='cuda:0')
Round: 2500 Training Error: tensor(252.2067, device='cuda:0') Validation Error: tensor(245.2995, device='cuda:0') Test Error: tensor(322.0571, device='cuda:0')
Round: 3000 Training Error: tensor(249.0945, device='cuda:0') Validation Error: tensor(248.5581, device='cuda:0') Test Error: tensor(319.9776, device='cuda:0')
Round: 3500 Training Error: tensor(247.2481, device='cuda:0') Validation Error: tensor(249.9835, device='cuda:0') Test Error: tensor(319.5109, device='cuda:0')
Round: 4000 Training Error: tensor(245.8680, device='cuda:0') Validation Error: tensor(250.7959, device='cuda:0') Test Error: tensor(319.2358, device='cuda:0')
Round: 4500 Training Error: tensor(244.3715, device='cuda:0') Validation Error: tensor(251.1007, device='cuda:0') Test Error: tensor(320.0209, device='cuda:0')
Round: 5000 Training Error: tensor(241.2833, device='cuda:0') Validation Error: tensor(251.3369, device='cuda:0') Test Error: tensor(317.2937, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dr', 'dw', 'hvac', 'mw']
Round: 500 Training Error: tensor(540.8490, device='cuda:0') Validation Error: tensor(494.5847, device='cuda:0') Test Error: tensor(603.4327, device='cuda:0')
Round: 1000 Training Error: tensor(421.1605, device='cuda:0') Validation Error: tensor(379.3484, device='cuda:0') Test Error: tensor(475.8927, device='cuda:0')
Round: 1500 Training Error: tensor(310.6628, device='cuda:0') Validation Error: tensor(274.2897, device='cuda:0') Test Error: tensor(364.9528, device='cuda:0')
Round: 2000 Training Error: tensor(263.4726, device='cuda:0') Validation Error: tensor(247.3062, device='cuda:0') Test Error: tensor(327.1641, device='cuda:0')
Round: 2500 Training Error: tensor(254.0995, device='cuda:0') Validation Error: tensor(251.1120, device='cuda:0') Test Error: tensor(321.8588, device='cuda:0')
Round: 3000 Training Error: tensor(251.1703, device='cuda:0') Validation Error: tensor(255.8293, device='cuda:0') Test Error: tensor(321.1095, device='cuda:0')
Round: 3500 Training Error: tensor(249.1678, device='cuda:0') Validation Error: tensor(257.8117, device='cuda:0') Test Error: tensor(320.6057, device='cuda:0')
Round: 4000 Training Error: tensor(247.6333, device='cuda:0') Validation Error: tensor(259.1458, device='cuda:0') Test Error: tensor(320.6897, device='cuda:0')
Round: 4500 Training Error: tensor(245.7513, device='cuda:0') Validation Error: tensor(259.5919, device='cuda:0') Test Error: tensor(320.1513, device='cuda:0')
Round: 5000 Training Error: tensor(243.4006, device='cuda:0') Validation Error: tensor(255.4083, device='cuda:0') Test Error: tensor(316.7691, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dr', 'dw', 'mw', 'hvac']
Round: 500 Training Error: tensor(540.5718, device='cuda:0') Validation Error: tensor(494.2812, device='cuda:0') Test Error: tensor(603.2091, device='cuda:0')
Round: 1000 Training Error: tensor(421.0742, device='cuda:0') Validation Error: tensor(380.2083, device='cuda:0') Test Error: tensor(475.3687, device='cuda:0')
Round: 1500 Training Error: tensor(310.3484, device='cuda:0') Validation Error: tensor(277.7316, device='cuda:0') Test Error: tensor(364.2597, device='cuda:0')
Round: 2000 Training Error: tensor(262.8279, device='cuda:0') Validation Error: tensor(249.4916, device='cuda:0') Test Error: tensor(324.2505, device='cuda:0')
Round: 2500 Training Error: tensor(253.0532, device='cuda:0') Validation Error: tensor(251.5895, device='cuda:0') Test Error: tensor(317.7467, device='cuda:0')
Round: 3000 Training Error: tensor(250.3867, device='cuda:0') Validation Error: tensor(254.6577, device='cuda:0') Test Error: tensor(316.7491, device='cuda:0')
Round: 3500 Training Error: tensor(248.1058, device='cuda:0') Validation Error: tensor(256.4447, device='cuda:0') Test Error: tensor(318.0563, device='cuda:0')
Round: 4000 Training Error: tensor(246.4097, device='cuda:0') Validation Error: tensor(258.1707, device='cuda:0') Test Error: tensor(317.2093, device='cuda:0')
Round: 4500 Training Error: tensor(244.3796, device='cuda:0') Validation Error: tensor(259.8763, device='cuda:0') Test Error: tensor(316.9830, device='cuda:0')
Round: 5000 Training Error: tensor(240.4812, device='cuda:0') Validation Error: tensor(260.9976, device='cuda:0') Test Error: tensor(312.8812, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dr', 'mw', 'hvac', 'dw']
Round: 500 Training Error: tensor(540.9531, device='cuda:0') Validation Error: tensor(494.6582, device='cuda:0') Test Error: tensor(603.3951, device='cuda:0')
Round: 1000 Training Error: tensor(421.2516, device='cuda:0') Validation Error: tensor(378.9040, device='cuda:0') Test Error: tensor(475.6029, device='cuda:0')
Round: 1500 Training Error: tensor(311.3144, device='cuda:0') Validation Error: tensor(273.2907, device='cuda:0') Test Error: tensor(362.8859, device='cuda:0')
Round: 2000 Training Error: tensor(263.2909, device='cuda:0') Validation Error: tensor(245.4622, device='cuda:0') Test Error: tensor(322.4823, device='cuda:0')
Round: 2500 Training Error: tensor(252.9590, device='cuda:0') Validation Error: tensor(251.9027, device='cuda:0') Test Error: tensor(314.5191, device='cuda:0')
Round: 3000 Training Error: tensor(249.9940, device='cuda:0') Validation Error: tensor(255.4678, device='cuda:0') Test Error: tensor(311.1330, device='cuda:0')
Round: 3500 Training Error: tensor(248.5142, device='cuda:0') Validation Error: tensor(259.2508, device='cuda:0') Test Error: tensor(311.7032, device='cuda:0')
Round: 4000 Training Error: tensor(247.2058, device='cuda:0') Validation Error: tensor(260.7025, device='cuda:0') Test Error: tensor(311.3621, device='cuda:0')
Round: 4500 Training Error: tensor(245.2668, device='cuda:0') Validation Error: tensor(260.1974, device='cuda:0') Test Error: tensor(310.6881, device='cuda:0')
Round: 5000 Training Error: tensor(242.8451, device='cuda:0') Validation Error: tensor(262.0641, device='cuda:0') Test Error: tensor(310.7192, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dr', 'mw', 'dw', 'hvac']
Round: 500 Training Error: tensor(540.6344, device='cuda:0') Validation Error: tensor(494.8398, device='cuda:0') Test Error: tensor(603.2527, device='cuda:0')
Round: 1000 Training Error: tensor(421.3278, device='cuda:0') Validation Error: tensor(378.7322, device='cuda:0') Test Error: tensor(475.4781, device='cuda:0')
Round: 1500 Training Error: tensor(310.3134, device='cuda:0') Validation Error: tensor(274.1304, device='cuda:0') Test Error: tensor(362.1939, device='cuda:0')
Round: 2000 Training Error: tensor(262.5977, device='cuda:0') Validation Error: tensor(248.2135, device='cuda:0') Test Error: tensor(321.2453, device='cuda:0')
Round: 2500 Training Error: tensor(252.9184, device='cuda:0') Validation Error: tensor(249.0782, device='cuda:0') Test Error: tensor(311.7105, device='cuda:0')
Round: 3000 Training Error: tensor(249.5943, device='cuda:0') Validation Error: tensor(252.6629, device='cuda:0') Test Error: tensor(310.9861, device='cuda:0')
Round: 3500 Training Error: tensor(248.0462, device='cuda:0') Validation Error: tensor(255.0788, device='cuda:0') Test Error: tensor(310.4131, device='cuda:0')
Round: 4000 Training Error: tensor(246.5381, device='cuda:0') Validation Error: tensor(256.4401, device='cuda:0') Test Error: tensor(311.1229, device='cuda:0')
Round: 4500 Training Error: tensor(244.9133, device='cuda:0') Validation Error: tensor(258.2581, device='cuda:0') Test Error: tensor(311.5703, device='cuda:0')
Round: 5000 Training Error: tensor(242.2945, device='cuda:0') Validation Error: tensor(257.9326, device='cuda:0') Test Error: tensor(309.0266, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dw', 'hvac', 'dr', 'mw']
Round: 500 Training Error: tensor(540.5581, device='cuda:0') Validation Error: tensor(494.8549, device='cuda:0') Test Error: tensor(603.0637, device='cuda:0')
Round: 1000 Training Error: tensor(420.6578, device='cuda:0') Validation Error: tensor(377.7348, device='cuda:0') Test Error: tensor(475.3482, device='cuda:0')
Round: 1500 Training Error: tensor(309.6490, device='cuda:0') Validation Error: tensor(270.9187, device='cuda:0') Test Error: tensor(362.4970, device='cuda:0')
Round: 2000 Training Error: tensor(262.6505, device='cuda:0') Validation Error: tensor(241.5016, device='cuda:0') Test Error: tensor(321.4518, device='cuda:0')
Round: 2500 Training Error: tensor(252.3181, device='cuda:0') Validation Error: tensor(246.0985, device='cuda:0') Test Error: tensor(316.4603, device='cuda:0')
Round: 3000 Training Error: tensor(249.6016, device='cuda:0') Validation Error: tensor(248.3964, device='cuda:0') Test Error: tensor(314.9885, device='cuda:0')
Round: 3500 Training Error: tensor(248.0119, device='cuda:0') Validation Error: tensor(250.9268, device='cuda:0') Test Error: tensor(316.2235, device='cuda:0')
Round: 4000 Training Error: tensor(246.3039, device='cuda:0') Validation Error: tensor(250.8997, device='cuda:0') Test Error: tensor(314.9087, device='cuda:0')
Round: 4500 Training Error: tensor(244.8073, device='cuda:0') Validation Error: tensor(251.9851, device='cuda:0') Test Error: tensor(316.4695, device='cuda:0')
Round: 5000 Training Error: tensor(241.9995, device='cuda:0') Validation Error: tensor(251.6646, device='cuda:0') Test Error: tensor(316.2279, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dw', 'hvac', 'mw', 'dr']
Round: 500 Training Error: tensor(540.5018, device='cuda:0') Validation Error: tensor(494.3136, device='cuda:0') Test Error: tensor(603.0596, device='cuda:0')
Round: 1000 Training Error: tensor(420.7988, device='cuda:0') Validation Error: tensor(377.2968, device='cuda:0') Test Error: tensor(475.2005, device='cuda:0')
Round: 1500 Training Error: tensor(308.8278, device='cuda:0') Validation Error: tensor(269.4625, device='cuda:0') Test Error: tensor(364.6773, device='cuda:0')
Round: 2000 Training Error: tensor(259.8492, device='cuda:0') Validation Error: tensor(246.8426, device='cuda:0') Test Error: tensor(326.4180, device='cuda:0')
Round: 2500 Training Error: tensor(250.8132, device='cuda:0') Validation Error: tensor(251.1234, device='cuda:0') Test Error: tensor(319.0381, device='cuda:0')
Round: 3000 Training Error: tensor(247.8255, device='cuda:0') Validation Error: tensor(254.9555, device='cuda:0') Test Error: tensor(319.1304, device='cuda:0')
Round: 3500 Training Error: tensor(246.4684, device='cuda:0') Validation Error: tensor(258.0251, device='cuda:0') Test Error: tensor(318.6021, device='cuda:0')
Round: 4000 Training Error: tensor(245.2752, device='cuda:0') Validation Error: tensor(257.6497, device='cuda:0') Test Error: tensor(320.8925, device='cuda:0')
Round: 4500 Training Error: tensor(244.1028, device='cuda:0') Validation Error: tensor(260.1046, device='cuda:0') Test Error: tensor(319.4597, device='cuda:0')
Round: 5000 Training Error: tensor(241.7576, device='cuda:0') Validation Error: tensor(257.0057, device='cuda:0') Test Error: tensor(321.6502, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dw', 'dr', 'hvac', 'mw']
Round: 500 Training Error: tensor(540.8915, device='cuda:0') Validation Error: tensor(494.9135, device='cuda:0') Test Error: tensor(603.2460, device='cuda:0')
Round: 1000 Training Error: tensor(420.9150, device='cuda:0') Validation Error: tensor(378.3094, device='cuda:0') Test Error: tensor(475.5056, device='cuda:0')
Round: 1500 Training Error: tensor(310.6122, device='cuda:0') Validation Error: tensor(272.7350, device='cuda:0') Test Error: tensor(362.1487, device='cuda:0')
Round: 2000 Training Error: tensor(263.1044, device='cuda:0') Validation Error: tensor(244.2962, device='cuda:0') Test Error: tensor(321.8358, device='cuda:0')
Round: 2500 Training Error: tensor(252.7544, device='cuda:0') Validation Error: tensor(249.4722, device='cuda:0') Test Error: tensor(313.7120, device='cuda:0')
Round: 3000 Training Error: tensor(250.0123, device='cuda:0') Validation Error: tensor(254.1957, device='cuda:0') Test Error: tensor(314.7043, device='cuda:0')
Round: 3500 Training Error: tensor(248.5204, device='cuda:0') Validation Error: tensor(254.6523, device='cuda:0') Test Error: tensor(313.8553, device='cuda:0')
Round: 4000 Training Error: tensor(246.9825, device='cuda:0') Validation Error: tensor(256.4448, device='cuda:0') Test Error: tensor(314.7264, device='cuda:0')
Round: 4500 Training Error: tensor(245.0434, device='cuda:0') Validation Error: tensor(256.3336, device='cuda:0') Test Error: tensor(313.2900, device='cuda:0')
Round: 5000 Training Error: tensor(242.6005, device='cuda:0') Validation Error: tensor(256.8212, device='cuda:0') Test Error: tensor(310.2997, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dw', 'dr', 'mw', 'hvac']
Round: 500 Training Error: tensor(540.5881, device='cuda:0') Validation Error: tensor(494.5381, device='cuda:0') Test Error: tensor(603., device='cuda:0')
Round: 1000 Training Error: tensor(420.7932, device='cuda:0') Validation Error: tensor(377.7066, device='cuda:0') Test Error: tensor(475.0865, device='cuda:0')
Round: 1500 Training Error: tensor(309.1008, device='cuda:0') Validation Error: tensor(271.3839, device='cuda:0') Test Error: tensor(364.6663, device='cuda:0')
Round: 2000 Training Error: tensor(260.5113, device='cuda:0') Validation Error: tensor(244.8461, device='cuda:0') Test Error: tensor(325.0592, device='cuda:0')
Round: 2500 Training Error: tensor(250.8149, device='cuda:0') Validation Error: tensor(246.7052, device='cuda:0') Test Error: tensor(321.1267, device='cuda:0')
Round: 3000 Training Error: tensor(247.8619, device='cuda:0') Validation Error: tensor(249.8922, device='cuda:0') Test Error: tensor(318.1579, device='cuda:0')
Round: 3500 Training Error: tensor(246.2177, device='cuda:0') Validation Error: tensor(252.0329, device='cuda:0') Test Error: tensor(318.0285, device='cuda:0')
Round: 4000 Training Error: tensor(245.1472, device='cuda:0') Validation Error: tensor(253.6946, device='cuda:0') Test Error: tensor(319.3820, device='cuda:0')
Round: 4500 Training Error: tensor(243.0626, device='cuda:0') Validation Error: tensor(253.6376, device='cuda:0') Test Error: tensor(316.4791, device='cuda:0')
Round: 5000 Training Error: tensor(239.1436, device='cuda:0') Validation Error: tensor(250.9827, device='cuda:0') Test Error: tensor(313.5389, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dw', 'mw', 'hvac', 'dr']
Round: 500 Training Error: tensor(540.7350, device='cuda:0') Validation Error: tensor(494.5176, device='cuda:0') Test Error: tensor(603.4359, device='cuda:0')
Round: 1000 Training Error: tensor(420.8346, device='cuda:0') Validation Error: tensor(379.0970, device='cuda:0') Test Error: tensor(475.6459, device='cuda:0')
Round: 1500 Training Error: tensor(310.2553, device='cuda:0') Validation Error: tensor(273.5449, device='cuda:0') Test Error: tensor(363.1905, device='cuda:0')
Round: 2000 Training Error: tensor(263.7434, device='cuda:0') Validation Error: tensor(247.0284, device='cuda:0') Test Error: tensor(323.5237, device='cuda:0')
Round: 2500 Training Error: tensor(254.1504, device='cuda:0') Validation Error: tensor(251.1046, device='cuda:0') Test Error: tensor(314.5326, device='cuda:0')
Round: 3000 Training Error: tensor(251.2773, device='cuda:0') Validation Error: tensor(256.3000, device='cuda:0') Test Error: tensor(314.1771, device='cuda:0')
Round: 3500 Training Error: tensor(249.2112, device='cuda:0') Validation Error: tensor(258.7660, device='cuda:0') Test Error: tensor(313.3699, device='cuda:0')
Round: 4000 Training Error: tensor(247.3501, device='cuda:0') Validation Error: tensor(260.2182, device='cuda:0') Test Error: tensor(312.4187, device='cuda:0')
Round: 4500 Training Error: tensor(245.0200, device='cuda:0') Validation Error: tensor(258.2270, device='cuda:0') Test Error: tensor(311.6312, device='cuda:0')
Round: 5000 Training Error: tensor(241.5278, device='cuda:0') Validation Error: tensor(256.4418, device='cuda:0') Test Error: tensor(310.2071, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'dw', 'mw', 'dr', 'hvac']
Round: 500 Training Error: tensor(540.4739, device='cuda:0') Validation Error: tensor(494.6848, device='cuda:0') Test Error: tensor(603.4104, device='cuda:0')
Round: 1000 Training Error: tensor(420.7057, device='cuda:0') Validation Error: tensor(378.8721, device='cuda:0') Test Error: tensor(476.3633, device='cuda:0')
Round: 1500 Training Error: tensor(310.5447, device='cuda:0') Validation Error: tensor(275.0204, device='cuda:0') Test Error: tensor(364.3334, device='cuda:0')
Round: 2000 Training Error: tensor(263.1375, device='cuda:0') Validation Error: tensor(241.5729, device='cuda:0') Test Error: tensor(322.9252, device='cuda:0')
Round: 2500 Training Error: tensor(252.1485, device='cuda:0') Validation Error: tensor(246.6410, device='cuda:0') Test Error: tensor(313.9193, device='cuda:0')
Round: 3000 Training Error: tensor(249.5014, device='cuda:0') Validation Error: tensor(250.1612, device='cuda:0') Test Error: tensor(313.6719, device='cuda:0')
Round: 3500 Training Error: tensor(248.0879, device='cuda:0') Validation Error: tensor(252.9972, device='cuda:0') Test Error: tensor(314.6316, device='cuda:0')
Round: 4000 Training Error: tensor(246.6342, device='cuda:0') Validation Error: tensor(254.4713, device='cuda:0') Test Error: tensor(314.5403, device='cuda:0')
Round: 4500 Training Error: tensor(244.6676, device='cuda:0') Validation Error: tensor(254.1783, device='cuda:0') Test Error: tensor(312.8443, device='cuda:0')
Round: 5000 Training Error: tensor(240.4802, device='cuda:0') Validation Error: tensor(252.7504, device='cuda:0') Test Error: tensor(310.8671, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'mw', 'hvac', 'dr', 'dw']
Round: 500 Training Error: tensor(540.5565, device='cuda:0') Validation Error: tensor(494.4499, device='cuda:0') Test Error: tensor(603.1985, device='cuda:0')
Round: 1000 Training Error: tensor(420.7334, device='cuda:0') Validation Error: tensor(377.8616, device='cuda:0') Test Error: tensor(475.3446, device='cuda:0')
Round: 1500 Training Error: tensor(309.3348, device='cuda:0') Validation Error: tensor(272.8058, device='cuda:0') Test Error: tensor(365.1584, device='cuda:0')
Round: 2000 Training Error: tensor(260.7893, device='cuda:0') Validation Error: tensor(248.1764, device='cuda:0') Test Error: tensor(327.0335, device='cuda:0')
Round: 2500 Training Error: tensor(250.3713, device='cuda:0') Validation Error: tensor(251.5946, device='cuda:0') Test Error: tensor(320.0322, device='cuda:0')
Round: 3000 Training Error: tensor(247.7192, device='cuda:0') Validation Error: tensor(252.9457, device='cuda:0') Test Error: tensor(319.6748, device='cuda:0')
Round: 3500 Training Error: tensor(245.9952, device='cuda:0') Validation Error: tensor(255.8606, device='cuda:0') Test Error: tensor(318.8322, device='cuda:0')
Round: 4000 Training Error: tensor(244.7955, device='cuda:0') Validation Error: tensor(257.1058, device='cuda:0') Test Error: tensor(319.2839, device='cuda:0')
Round: 4500 Training Error: tensor(243.4118, device='cuda:0') Validation Error: tensor(257.1324, device='cuda:0') Test Error: tensor(319.2512, device='cuda:0')
Round: 5000 Training Error: tensor(240.5245, device='cuda:0') Validation Error: tensor(256.8618, device='cuda:0') Test Error: tensor(317.4822, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'mw', 'hvac', 'dw', 'dr']
Round: 500 Training Error: tensor(540.3911, device='cuda:0') Validation Error: tensor(494.4320, device='cuda:0') Test Error: tensor(603.1698, device='cuda:0')
Round: 1000 Training Error: tensor(420.5927, device='cuda:0') Validation Error: tensor(377.9987, device='cuda:0') Test Error: tensor(475.0535, device='cuda:0')
Round: 1500 Training Error: tensor(309.6535, device='cuda:0') Validation Error: tensor(271.8411, device='cuda:0') Test Error: tensor(365.2043, device='cuda:0')
Round: 2000 Training Error: tensor(262.4448, device='cuda:0') Validation Error: tensor(244.7522, device='cuda:0') Test Error: tensor(326.4686, device='cuda:0')
Round: 2500 Training Error: tensor(252.6931, device='cuda:0') Validation Error: tensor(249.3056, device='cuda:0') Test Error: tensor(319.9278, device='cuda:0')
Round: 3000 Training Error: tensor(249.5322, device='cuda:0') Validation Error: tensor(253.3847, device='cuda:0') Test Error: tensor(318.1895, device='cuda:0')
Round: 3500 Training Error: tensor(248.2850, device='cuda:0') Validation Error: tensor(253.4825, device='cuda:0') Test Error: tensor(321.3621, device='cuda:0')
Round: 4000 Training Error: tensor(246.6558, device='cuda:0') Validation Error: tensor(254.7487, device='cuda:0') Test Error: tensor(320.5346, device='cuda:0')
Round: 4500 Training Error: tensor(244.9994, device='cuda:0') Validation Error: tensor(254.8882, device='cuda:0') Test Error: tensor(320.8112, device='cuda:0')
Round: 5000 Training Error: tensor(241.8789, device='cuda:0') Validation Error: tensor(255.8224, device='cuda:0') Test Error: tensor(318.1817, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'mw', 'dr', 'hvac', 'dw']
Round: 500 Training Error: tensor(540.9214, device='cuda:0') Validation Error: tensor(494.5918, device='cuda:0') Test Error: tensor(603.2736, device='cuda:0')
Round: 1000 Training Error: tensor(420.9310, device='cuda:0') Validation Error: tensor(379.2404, device='cuda:0') Test Error: tensor(475.5980, device='cuda:0')
Round: 1500 Training Error: tensor(310.4250, device='cuda:0') Validation Error: tensor(273.3972, device='cuda:0') Test Error: tensor(362.7189, device='cuda:0')
Round: 2000 Training Error: tensor(263.5389, device='cuda:0') Validation Error: tensor(245.6830, device='cuda:0') Test Error: tensor(322.7817, device='cuda:0')
Round: 2500 Training Error: tensor(252.7939, device='cuda:0') Validation Error: tensor(252.7571, device='cuda:0') Test Error: tensor(316.3804, device='cuda:0')
Round: 3000 Training Error: tensor(249.9242, device='cuda:0') Validation Error: tensor(256.3539, device='cuda:0') Test Error: tensor(316.2924, device='cuda:0')
Round: 3500 Training Error: tensor(248.2850, device='cuda:0') Validation Error: tensor(257.6331, device='cuda:0') Test Error: tensor(315.3987, device='cuda:0')
Round: 4000 Training Error: tensor(246.5533, device='cuda:0') Validation Error: tensor(258.4358, device='cuda:0') Test Error: tensor(314.1523, device='cuda:0')
Round: 4500 Training Error: tensor(244.6538, device='cuda:0') Validation Error: tensor(256.6972, device='cuda:0') Test Error: tensor(312.5601, device='cuda:0')
Round: 5000 Training Error: tensor(242.1696, device='cuda:0') Validation Error: tensor(255.6599, device='cuda:0') Test Error: tensor(311.6820, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'mw', 'dr', 'dw', 'hvac']
Round: 500 Training Error: tensor(540.5082, device='cuda:0') Validation Error: tensor(494.4075, device='cuda:0') Test Error: tensor(603.1159, device='cuda:0')
Round: 1000 Training Error: tensor(420.7390, device='cuda:0') Validation Error: tensor(378.2173, device='cuda:0') Test Error: tensor(475.4915, device='cuda:0')
Round: 1500 Training Error: tensor(309.7500, device='cuda:0') Validation Error: tensor(272.1646, device='cuda:0') Test Error: tensor(363.9503, device='cuda:0')
Round: 2000 Training Error: tensor(261.4925, device='cuda:0') Validation Error: tensor(245.4756, device='cuda:0') Test Error: tensor(324.4641, device='cuda:0')
Round: 2500 Training Error: tensor(252.4005, device='cuda:0') Validation Error: tensor(247.1289, device='cuda:0') Test Error: tensor(316.5493, device='cuda:0')
Round: 3000 Training Error: tensor(249.9180, device='cuda:0') Validation Error: tensor(250.9675, device='cuda:0') Test Error: tensor(314.0081, device='cuda:0')
Round: 3500 Training Error: tensor(248.3910, device='cuda:0') Validation Error: tensor(253.0224, device='cuda:0') Test Error: tensor(313.4751, device='cuda:0')
Round: 4000 Training Error: tensor(247.1158, device='cuda:0') Validation Error: tensor(254.6325, device='cuda:0') Test Error: tensor(312.0900, device='cuda:0')
Round: 4500 Training Error: tensor(245.4840, device='cuda:0') Validation Error: tensor(256.6044, device='cuda:0') Test Error: tensor(312.7230, device='cuda:0')
Round: 5000 Training Error: tensor(242.3102, device='cuda:0') Validation Error: tensor(256.2160, device='cuda:0') Test Error: tensor(308.8873, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'mw', 'dw', 'hvac', 'dr']
Round: 500 Training Error: tensor(540.8865, device='cuda:0') Validation Error: tensor(494.8812, device='cuda:0') Test Error: tensor(603.1776, device='cuda:0')
Round: 1000 Training Error: tensor(420.9568, device='cuda:0') Validation Error: tensor(378.4113, device='cuda:0') Test Error: tensor(475.4100, device='cuda:0')
Round: 1500 Training Error: tensor(310.9842, device='cuda:0') Validation Error: tensor(271.8344, device='cuda:0') Test Error: tensor(362.4077, device='cuda:0')
Round: 2000 Training Error: tensor(263.7207, device='cuda:0') Validation Error: tensor(242.4780, device='cuda:0') Test Error: tensor(322.8326, device='cuda:0')
Round: 2500 Training Error: tensor(254.0727, device='cuda:0') Validation Error: tensor(249.4606, device='cuda:0') Test Error: tensor(317.8926, device='cuda:0')
Round: 3000 Training Error: tensor(251.1020, device='cuda:0') Validation Error: tensor(253.9995, device='cuda:0') Test Error: tensor(316.8606, device='cuda:0')
Round: 3500 Training Error: tensor(249.3222, device='cuda:0') Validation Error: tensor(257.7320, device='cuda:0') Test Error: tensor(317.2057, device='cuda:0')
Round: 4000 Training Error: tensor(248.1105, device='cuda:0') Validation Error: tensor(257.2646, device='cuda:0') Test Error: tensor(315.4716, device='cuda:0')
Round: 4500 Training Error: tensor(246.5691, device='cuda:0') Validation Error: tensor(255.3450, device='cuda:0') Test Error: tensor(313.4830, device='cuda:0')
Round: 5000 Training Error: tensor(244.3290, device='cuda:0') Validation Error: tensor(255.0483, device='cuda:0') Test Error: tensor(312.2328, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['fridge', 'mw', 'dw', 'dr', 'hvac']
Round: 500 Training Error: tensor(540.5973, device='cuda:0') Validation Error: tensor(495.0357, device='cuda:0') Test Error: tensor(603.2353, device='cuda:0')
Round: 1000 Training Error: tensor(420.8246, device='cuda:0') Validation Error: tensor(378.2319, device='cuda:0') Test Error: tensor(475.6529, device='cuda:0')
Round: 1500 Training Error: tensor(310.9239, device='cuda:0') Validation Error: tensor(273.7162, device='cuda:0') Test Error: tensor(363.1153, device='cuda:0')
Round: 2000 Training Error: tensor(261.3730, device='cuda:0') Validation Error: tensor(245.8372, device='cuda:0') Test Error: tensor(323.7245, device='cuda:0')
Round: 2500 Training Error: tensor(251.3769, device='cuda:0') Validation Error: tensor(248.6228, device='cuda:0') Test Error: tensor(315.6803, device='cuda:0')
Round: 3000 Training Error: tensor(249.1568, device='cuda:0') Validation Error: tensor(249.4068, device='cuda:0') Test Error: tensor(313.7294, device='cuda:0')
Round: 3500 Training Error: tensor(247.7390, device='cuda:0') Validation Error: tensor(249.2182, device='cuda:0') Test Error: tensor(312.8251, device='cuda:0')
Round: 4000 Training Error: tensor(246.1824, device='cuda:0') Validation Error: tensor(249.4871, device='cuda:0') Test Error: tensor(312.9401, device='cuda:0')
Round: 4500 Training Error: tensor(244.2712, device='cuda:0') Validation Error: tensor(249.4423, device='cuda:0') Test Error: tensor(312.1162, device='cuda:0')
Round: 5000 Training Error: tensor(241.8098, device='cuda:0') Validation Error: tensor(247.0527, device='cuda:0') Test Error: tensor(311.4839, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'hvac', 'fridge', 'dr', 'mw']
Round: 500 Training Error: tensor(540.5278, device='cuda:0') Validation Error: tensor(494.5471, device='cuda:0') Test Error: tensor(602.8522, device='cuda:0')
Round: 1000 Training Error: tensor(421.3817, device='cuda:0') Validation Error: tensor(379.9478, device='cuda:0') Test Error: tensor(475.4142, device='cuda:0')
Round: 1500 Training Error: tensor(310.9147, device='cuda:0') Validation Error: tensor(275.1418, device='cuda:0') Test Error: tensor(364.9424, device='cuda:0')
Round: 2000 Training Error: tensor(263.4800, device='cuda:0') Validation Error: tensor(248.0208, device='cuda:0') Test Error: tensor(327.0812, device='cuda:0')
Round: 2500 Training Error: tensor(253.5464, device='cuda:0') Validation Error: tensor(248.9570, device='cuda:0') Test Error: tensor(317.8228, device='cuda:0')
Round: 3000 Training Error: tensor(251.1640, device='cuda:0') Validation Error: tensor(251.0546, device='cuda:0') Test Error: tensor(317.0464, device='cuda:0')
Round: 3500 Training Error: tensor(250.2247, device='cuda:0') Validation Error: tensor(251.9934, device='cuda:0') Test Error: tensor(317.6979, device='cuda:0')
Round: 4000 Training Error: tensor(248.9748, device='cuda:0') Validation Error: tensor(252.1117, device='cuda:0') Test Error: tensor(317.1648, device='cuda:0')
Round: 4500 Training Error: tensor(247.1553, device='cuda:0') Validation Error: tensor(251.1290, device='cuda:0') Test Error: tensor(314.6043, device='cuda:0')
Round: 5000 Training Error: tensor(243.7741, device='cuda:0') Validation Error: tensor(249.5831, device='cuda:0') Test Error: tensor(312.9693, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'hvac', 'fridge', 'mw', 'dr']
Round: 500 Training Error: tensor(540.4752, device='cuda:0') Validation Error: tensor(494.5081, device='cuda:0') Test Error: tensor(602.8673, device='cuda:0')
Round: 1000 Training Error: tensor(421.3618, device='cuda:0') Validation Error: tensor(379.3504, device='cuda:0') Test Error: tensor(475.6170, device='cuda:0')
Round: 1500 Training Error: tensor(310.9342, device='cuda:0') Validation Error: tensor(273.8087, device='cuda:0') Test Error: tensor(363.4536, device='cuda:0')
Round: 2000 Training Error: tensor(263.7501, device='cuda:0') Validation Error: tensor(248.5561, device='cuda:0') Test Error: tensor(324.3425, device='cuda:0')
Round: 2500 Training Error: tensor(253.8277, device='cuda:0') Validation Error: tensor(249.7176, device='cuda:0') Test Error: tensor(315.3753, device='cuda:0')
Round: 3000 Training Error: tensor(251.0165, device='cuda:0') Validation Error: tensor(253.0449, device='cuda:0') Test Error: tensor(317.0077, device='cuda:0')
Round: 3500 Training Error: tensor(249.8012, device='cuda:0') Validation Error: tensor(254.1286, device='cuda:0') Test Error: tensor(316.9747, device='cuda:0')
Round: 4000 Training Error: tensor(248.4776, device='cuda:0') Validation Error: tensor(256.6570, device='cuda:0') Test Error: tensor(317.6834, device='cuda:0')
Round: 4500 Training Error: tensor(246.4853, device='cuda:0') Validation Error: tensor(258.1122, device='cuda:0') Test Error: tensor(317.3486, device='cuda:0')
Round: 5000 Training Error: tensor(242.8709, device='cuda:0') Validation Error: tensor(255.9943, device='cuda:0') Test Error: tensor(314.4360, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'hvac', 'dr', 'fridge', 'mw']
Round: 500 Training Error: tensor(540.4670, device='cuda:0') Validation Error: tensor(494.4982, device='cuda:0') Test Error: tensor(602.8214, device='cuda:0')
Round: 1000 Training Error: tensor(421.3438, device='cuda:0') Validation Error: tensor(378.7979, device='cuda:0') Test Error: tensor(475.3728, device='cuda:0')
Round: 1500 Training Error: tensor(310.9782, device='cuda:0') Validation Error: tensor(272.7753, device='cuda:0') Test Error: tensor(363.8878, device='cuda:0')
Round: 2000 Training Error: tensor(264.0558, device='cuda:0') Validation Error: tensor(247.8067, device='cuda:0') Test Error: tensor(323.4818, device='cuda:0')
Round: 2500 Training Error: tensor(253.3177, device='cuda:0') Validation Error: tensor(248.6567, device='cuda:0') Test Error: tensor(317.9412, device='cuda:0')
Round: 3000 Training Error: tensor(250.7096, device='cuda:0') Validation Error: tensor(249.5262, device='cuda:0') Test Error: tensor(316.8832, device='cuda:0')
Round: 3500 Training Error: tensor(249.7054, device='cuda:0') Validation Error: tensor(250.0971, device='cuda:0') Test Error: tensor(316.7595, device='cuda:0')
Round: 4000 Training Error: tensor(248.3587, device='cuda:0') Validation Error: tensor(248.9510, device='cuda:0') Test Error: tensor(314.7699, device='cuda:0')
Round: 4500 Training Error: tensor(246.3422, device='cuda:0') Validation Error: tensor(249.5041, device='cuda:0') Test Error: tensor(314.1458, device='cuda:0')
Round: 5000 Training Error: tensor(242.6883, device='cuda:0') Validation Error: tensor(248.0862, device='cuda:0') Test Error: tensor(312.3847, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'hvac', 'dr', 'mw', 'fridge']
Round: 500 Training Error: tensor(540.8288, device='cuda:0') Validation Error: tensor(494.4155, device='cuda:0') Test Error: tensor(603.0413, device='cuda:0')
Round: 1000 Training Error: tensor(421.2510, device='cuda:0') Validation Error: tensor(379.0840, device='cuda:0') Test Error: tensor(475.2612, device='cuda:0')
Round: 1500 Training Error: tensor(310.5614, device='cuda:0') Validation Error: tensor(271.7125, device='cuda:0') Test Error: tensor(364.1589, device='cuda:0')
Round: 2000 Training Error: tensor(264.1304, device='cuda:0') Validation Error: tensor(242.7701, device='cuda:0') Test Error: tensor(324.3310, device='cuda:0')
Round: 2500 Training Error: tensor(255.3984, device='cuda:0') Validation Error: tensor(244.6534, device='cuda:0') Test Error: tensor(317.9726, device='cuda:0')
Round: 3000 Training Error: tensor(252.8227, device='cuda:0') Validation Error: tensor(246.0631, device='cuda:0') Test Error: tensor(317.4266, device='cuda:0')
Round: 3500 Training Error: tensor(251.5102, device='cuda:0') Validation Error: tensor(247.8805, device='cuda:0') Test Error: tensor(319.2606, device='cuda:0')
Round: 4000 Training Error: tensor(250.2458, device='cuda:0') Validation Error: tensor(248.3776, device='cuda:0') Test Error: tensor(319.1103, device='cuda:0')
Round: 4500 Training Error: tensor(248.3917, device='cuda:0') Validation Error: tensor(248.2728, device='cuda:0') Test Error: tensor(318.8167, device='cuda:0')
Round: 5000 Training Error: tensor(245.8330, device='cuda:0') Validation Error: tensor(246.7808, device='cuda:0') Test Error: tensor(315.7593, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'hvac', 'mw', 'fridge', 'dr']
Round: 500 Training Error: tensor(540.4462, device='cuda:0') Validation Error: tensor(494.7071, device='cuda:0') Test Error: tensor(602.9762, device='cuda:0')
Round: 1000 Training Error: tensor(421.3582, device='cuda:0') Validation Error: tensor(378.3247, device='cuda:0') Test Error: tensor(474.7025, device='cuda:0')
Round: 1500 Training Error: tensor(310.9184, device='cuda:0') Validation Error: tensor(274.4723, device='cuda:0') Test Error: tensor(365.0861, device='cuda:0')
Round: 2000 Training Error: tensor(263.7365, device='cuda:0') Validation Error: tensor(247.6762, device='cuda:0') Test Error: tensor(327.9804, device='cuda:0')
Round: 2500 Training Error: tensor(253.6385, device='cuda:0') Validation Error: tensor(247.6989, device='cuda:0') Test Error: tensor(319.7960, device='cuda:0')
Round: 3000 Training Error: tensor(251.3066, device='cuda:0') Validation Error: tensor(249.6742, device='cuda:0') Test Error: tensor(317.7292, device='cuda:0')
Round: 3500 Training Error: tensor(249.7458, device='cuda:0') Validation Error: tensor(253.0874, device='cuda:0') Test Error: tensor(317.9307, device='cuda:0')
Round: 4000 Training Error: tensor(248.1003, device='cuda:0') Validation Error: tensor(253.6112, device='cuda:0') Test Error: tensor(315.3912, device='cuda:0')
Round: 4500 Training Error: tensor(246.1554, device='cuda:0') Validation Error: tensor(255.5439, device='cuda:0') Test Error: tensor(315.4532, device='cuda:0')
Round: 5000 Training Error: tensor(242.3878, device='cuda:0') Validation Error: tensor(254.6353, device='cuda:0') Test Error: tensor(312.7464, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'hvac', 'mw', 'dr', 'fridge']
Round: 500 Training Error: tensor(540.8764, device='cuda:0') Validation Error: tensor(494.5886, device='cuda:0') Test Error: tensor(603.1970, device='cuda:0')
Round: 1000 Training Error: tensor(421.4947, device='cuda:0') Validation Error: tensor(378.9044, device='cuda:0') Test Error: tensor(475.4815, device='cuda:0')
Round: 1500 Training Error: tensor(311.1284, device='cuda:0') Validation Error: tensor(275.1335, device='cuda:0') Test Error: tensor(363.9064, device='cuda:0')
Round: 2000 Training Error: tensor(264.8304, device='cuda:0') Validation Error: tensor(245.8239, device='cuda:0') Test Error: tensor(322.9461, device='cuda:0')
Round: 2500 Training Error: tensor(255.4813, device='cuda:0') Validation Error: tensor(246.3302, device='cuda:0') Test Error: tensor(313.2722, device='cuda:0')
Round: 3000 Training Error: tensor(253.2589, device='cuda:0') Validation Error: tensor(247.3257, device='cuda:0') Test Error: tensor(310.8144, device='cuda:0')
Round: 3500 Training Error: tensor(251.7154, device='cuda:0') Validation Error: tensor(248.9844, device='cuda:0') Test Error: tensor(310.8965, device='cuda:0')
Round: 4000 Training Error: tensor(250.0800, device='cuda:0') Validation Error: tensor(249.3794, device='cuda:0') Test Error: tensor(311.0845, device='cuda:0')
Round: 4500 Training Error: tensor(248.5803, device='cuda:0') Validation Error: tensor(249.7340, device='cuda:0') Test Error: tensor(309.8990, device='cuda:0')
Round: 5000 Training Error: tensor(245.6481, device='cuda:0') Validation Error: tensor(250.3416, device='cuda:0') Test Error: tensor(308.5892, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'fridge', 'hvac', 'dr', 'mw']
Round: 500 Training Error: tensor(540.8817, device='cuda:0') Validation Error: tensor(494.7211, device='cuda:0') Test Error: tensor(603.4159, device='cuda:0')
Round: 1000 Training Error: tensor(420.6488, device='cuda:0') Validation Error: tensor(378.3181, device='cuda:0') Test Error: tensor(475.6309, device='cuda:0')
Round: 1500 Training Error: tensor(309.3222, device='cuda:0') Validation Error: tensor(272.5954, device='cuda:0') Test Error: tensor(365.2407, device='cuda:0')
Round: 2000 Training Error: tensor(262.7639, device='cuda:0') Validation Error: tensor(244.1428, device='cuda:0') Test Error: tensor(328.7105, device='cuda:0')
Round: 2500 Training Error: tensor(253.0677, device='cuda:0') Validation Error: tensor(248.7149, device='cuda:0') Test Error: tensor(320.4277, device='cuda:0')
Round: 3000 Training Error: tensor(250.1748, device='cuda:0') Validation Error: tensor(252.9445, device='cuda:0') Test Error: tensor(316.5192, device='cuda:0')
Round: 3500 Training Error: tensor(248.4060, device='cuda:0') Validation Error: tensor(253.4383, device='cuda:0') Test Error: tensor(316.8569, device='cuda:0')
Round: 4000 Training Error: tensor(246.7179, device='cuda:0') Validation Error: tensor(255.1722, device='cuda:0') Test Error: tensor(316.7464, device='cuda:0')
Round: 4500 Training Error: tensor(245.0915, device='cuda:0') Validation Error: tensor(255.8601, device='cuda:0') Test Error: tensor(315.3993, device='cuda:0')
Round: 5000 Training Error: tensor(242.6783, device='cuda:0') Validation Error: tensor(255.3556, device='cuda:0') Test Error: tensor(314.2812, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'fridge', 'hvac', 'mw', 'dr']
Round: 500 Training Error: tensor(540.8143, device='cuda:0') Validation Error: tensor(494.5266, device='cuda:0') Test Error: tensor(603.4521, device='cuda:0')
Round: 1000 Training Error: tensor(420.5436, device='cuda:0') Validation Error: tensor(377.4461, device='cuda:0') Test Error: tensor(475.4001, device='cuda:0')
Round: 1500 Training Error: tensor(309.4473, device='cuda:0') Validation Error: tensor(270.8626, device='cuda:0') Test Error: tensor(364.3438, device='cuda:0')
Round: 2000 Training Error: tensor(262.1430, device='cuda:0') Validation Error: tensor(243.4040, device='cuda:0') Test Error: tensor(325.4332, device='cuda:0')
Round: 2500 Training Error: tensor(251.8979, device='cuda:0') Validation Error: tensor(248.9567, device='cuda:0') Test Error: tensor(316.5910, device='cuda:0')
Round: 3000 Training Error: tensor(248.2019, device='cuda:0') Validation Error: tensor(254.9621, device='cuda:0') Test Error: tensor(315.9568, device='cuda:0')
Round: 3500 Training Error: tensor(246.4330, device='cuda:0') Validation Error: tensor(258.5832, device='cuda:0') Test Error: tensor(316.3251, device='cuda:0')
Round: 4000 Training Error: tensor(245.4948, device='cuda:0') Validation Error: tensor(258.5595, device='cuda:0') Test Error: tensor(317.9396, device='cuda:0')
Round: 4500 Training Error: tensor(244.0128, device='cuda:0') Validation Error: tensor(262.6979, device='cuda:0') Test Error: tensor(314.9338, device='cuda:0')
Round: 5000 Training Error: tensor(241.4043, device='cuda:0') Validation Error: tensor(258.3575, device='cuda:0') Test Error: tensor(315.3880, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'fridge', 'dr', 'hvac', 'mw']
Round: 500 Training Error: tensor(541.2109, device='cuda:0') Validation Error: tensor(494.8086, device='cuda:0') Test Error: tensor(603.5912, device='cuda:0')
Round: 1000 Training Error: tensor(420.8672, device='cuda:0') Validation Error: tensor(378.6710, device='cuda:0') Test Error: tensor(475.5545, device='cuda:0')
Round: 1500 Training Error: tensor(309.9780, device='cuda:0') Validation Error: tensor(271.9778, device='cuda:0') Test Error: tensor(364.5391, device='cuda:0')
Round: 2000 Training Error: tensor(263.7398, device='cuda:0') Validation Error: tensor(246.7769, device='cuda:0') Test Error: tensor(325.0861, device='cuda:0')
Round: 2500 Training Error: tensor(253.2615, device='cuda:0') Validation Error: tensor(252.2381, device='cuda:0') Test Error: tensor(318.0176, device='cuda:0')
Round: 3000 Training Error: tensor(250.2850, device='cuda:0') Validation Error: tensor(251.9125, device='cuda:0') Test Error: tensor(314.2808, device='cuda:0')
Round: 3500 Training Error: tensor(248.8255, device='cuda:0') Validation Error: tensor(253.9066, device='cuda:0') Test Error: tensor(315.2858, device='cuda:0')
Round: 4000 Training Error: tensor(247.4674, device='cuda:0') Validation Error: tensor(252.7235, device='cuda:0') Test Error: tensor(314.0594, device='cuda:0')
Round: 4500 Training Error: tensor(245.7800, device='cuda:0') Validation Error: tensor(254.4792, device='cuda:0') Test Error: tensor(313.5811, device='cuda:0')
Round: 5000 Training Error: tensor(242.9736, device='cuda:0') Validation Error: tensor(252.3147, device='cuda:0') Test Error: tensor(311.8380, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'fridge', 'dr', 'mw', 'hvac']
Round: 500 Training Error: tensor(540.9680, device='cuda:0') Validation Error: tensor(494.5610, device='cuda:0') Test Error: tensor(603.3700, device='cuda:0')
Round: 1000 Training Error: tensor(420.6667, device='cuda:0') Validation Error: tensor(378.0188, device='cuda:0') Test Error: tensor(475.3529, device='cuda:0')
Round: 1500 Training Error: tensor(309.9536, device='cuda:0') Validation Error: tensor(272.2209, device='cuda:0') Test Error: tensor(363.1457, device='cuda:0')
Round: 2000 Training Error: tensor(261.6567, device='cuda:0') Validation Error: tensor(243.8673, device='cuda:0') Test Error: tensor(325.9096, device='cuda:0')
Round: 2500 Training Error: tensor(251.4520, device='cuda:0') Validation Error: tensor(245.6312, device='cuda:0') Test Error: tensor(318.2192, device='cuda:0')
Round: 3000 Training Error: tensor(248.3576, device='cuda:0') Validation Error: tensor(250.6514, device='cuda:0') Test Error: tensor(316.5195, device='cuda:0')
Round: 3500 Training Error: tensor(246.7164, device='cuda:0') Validation Error: tensor(251.5801, device='cuda:0') Test Error: tensor(315.0649, device='cuda:0')
Round: 4000 Training Error: tensor(245.3864, device='cuda:0') Validation Error: tensor(252.6727, device='cuda:0') Test Error: tensor(314.7018, device='cuda:0')
Round: 4500 Training Error: tensor(243.4667, device='cuda:0') Validation Error: tensor(253.3074, device='cuda:0') Test Error: tensor(313.2184, device='cuda:0')
Round: 5000 Training Error: tensor(240.2562, device='cuda:0') Validation Error: tensor(251.8479, device='cuda:0') Test Error: tensor(310.7284, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'fridge', 'mw', 'hvac', 'dr']
Round: 500 Training Error: tensor(541.1494, device='cuda:0') Validation Error: tensor(494.6383, device='cuda:0') Test Error: tensor(603.5811, device='cuda:0')
Round: 1000 Training Error: tensor(420.7731, device='cuda:0') Validation Error: tensor(378.4606, device='cuda:0') Test Error: tensor(475.4902, device='cuda:0')
Round: 1500 Training Error: tensor(309.9368, device='cuda:0') Validation Error: tensor(270.9411, device='cuda:0') Test Error: tensor(363.9687, device='cuda:0')
Round: 2000 Training Error: tensor(264.6022, device='cuda:0') Validation Error: tensor(244.1724, device='cuda:0') Test Error: tensor(325.0487, device='cuda:0')
Round: 2500 Training Error: tensor(253.2091, device='cuda:0') Validation Error: tensor(249.8387, device='cuda:0') Test Error: tensor(318.6466, device='cuda:0')
Round: 3000 Training Error: tensor(250.1965, device='cuda:0') Validation Error: tensor(252.7538, device='cuda:0') Test Error: tensor(316.9929, device='cuda:0')
Round: 3500 Training Error: tensor(248.3850, device='cuda:0') Validation Error: tensor(255.8503, device='cuda:0') Test Error: tensor(316.2367, device='cuda:0')
Round: 4000 Training Error: tensor(247.0679, device='cuda:0') Validation Error: tensor(258.1512, device='cuda:0') Test Error: tensor(316.2043, device='cuda:0')
Round: 4500 Training Error: tensor(245.5247, device='cuda:0') Validation Error: tensor(255.6712, device='cuda:0') Test Error: tensor(314.1003, device='cuda:0')
Round: 5000 Training Error: tensor(243.3196, device='cuda:0') Validation Error: tensor(256.6432, device='cuda:0') Test Error: tensor(314.2552, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'fridge', 'mw', 'dr', 'hvac']
Round: 500 Training Error: tensor(540.9149, device='cuda:0') Validation Error: tensor(494.7265, device='cuda:0') Test Error: tensor(603.4604, device='cuda:0')
Round: 1000 Training Error: tensor(420.9797, device='cuda:0') Validation Error: tensor(378.3648, device='cuda:0') Test Error: tensor(475.5372, device='cuda:0')
Round: 1500 Training Error: tensor(309.9950, device='cuda:0') Validation Error: tensor(276.8975, device='cuda:0') Test Error: tensor(362.2510, device='cuda:0')
Round: 2000 Training Error: tensor(262.1746, device='cuda:0') Validation Error: tensor(248.1917, device='cuda:0') Test Error: tensor(324.3962, device='cuda:0')
Round: 2500 Training Error: tensor(252.3119, device='cuda:0') Validation Error: tensor(251.4207, device='cuda:0') Test Error: tensor(316.2573, device='cuda:0')
Round: 3000 Training Error: tensor(249.7280, device='cuda:0') Validation Error: tensor(252.1438, device='cuda:0') Test Error: tensor(315.2068, device='cuda:0')
Round: 3500 Training Error: tensor(247.8694, device='cuda:0') Validation Error: tensor(253.4178, device='cuda:0') Test Error: tensor(315.4794, device='cuda:0')
Round: 4000 Training Error: tensor(246.3462, device='cuda:0') Validation Error: tensor(255.3532, device='cuda:0') Test Error: tensor(316.2912, device='cuda:0')
Round: 4500 Training Error: tensor(243.6979, device='cuda:0') Validation Error: tensor(255.9945, device='cuda:0') Test Error: tensor(314.4450, device='cuda:0')
Round: 5000 Training Error: tensor(240.8469, device='cuda:0') Validation Error: tensor(254.4216, device='cuda:0') Test Error: tensor(311.4968, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'dr', 'hvac', 'fridge', 'mw']
Round: 500 Training Error: tensor(540.5056, device='cuda:0') Validation Error: tensor(494.4290, device='cuda:0') Test Error: tensor(603.0146, device='cuda:0')
Round: 1000 Training Error: tensor(421.3675, device='cuda:0') Validation Error: tensor(378.9776, device='cuda:0') Test Error: tensor(475.6902, device='cuda:0')
Round: 1500 Training Error: tensor(310.1228, device='cuda:0') Validation Error: tensor(275.1980, device='cuda:0') Test Error: tensor(366.5781, device='cuda:0')
Round: 2000 Training Error: tensor(261.7643, device='cuda:0') Validation Error: tensor(249.2170, device='cuda:0') Test Error: tensor(326.1168, device='cuda:0')
Round: 2500 Training Error: tensor(252.1843, device='cuda:0') Validation Error: tensor(251.3682, device='cuda:0') Test Error: tensor(318.8238, device='cuda:0')
Round: 3000 Training Error: tensor(248.9970, device='cuda:0') Validation Error: tensor(255.8631, device='cuda:0') Test Error: tensor(316.8531, device='cuda:0')
Round: 3500 Training Error: tensor(246.6904, device='cuda:0') Validation Error: tensor(256.9600, device='cuda:0') Test Error: tensor(319.1378, device='cuda:0')
Round: 4000 Training Error: tensor(245.0878, device='cuda:0') Validation Error: tensor(259.0380, device='cuda:0') Test Error: tensor(317.5125, device='cuda:0')
Round: 4500 Training Error: tensor(243.5422, device='cuda:0') Validation Error: tensor(257.9893, device='cuda:0') Test Error: tensor(318.1581, device='cuda:0')
Round: 5000 Training Error: tensor(240.6217, device='cuda:0') Validation Error: tensor(255.8610, device='cuda:0') Test Error: tensor(317.0500, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'dr', 'hvac', 'mw', 'fridge']
Round: 500 Training Error: tensor(540.8842, device='cuda:0') Validation Error: tensor(494.3081, device='cuda:0') Test Error: tensor(603.1554, device='cuda:0')
Round: 1000 Training Error: tensor(421.3349, device='cuda:0') Validation Error: tensor(378.1958, device='cuda:0') Test Error: tensor(475.6859, device='cuda:0')
Round: 1500 Training Error: tensor(309.9861, device='cuda:0') Validation Error: tensor(272.0249, device='cuda:0') Test Error: tensor(365.9688, device='cuda:0')
Round: 2000 Training Error: tensor(261.9659, device='cuda:0') Validation Error: tensor(244.4290, device='cuda:0') Test Error: tensor(326.5193, device='cuda:0')
Round: 2500 Training Error: tensor(251.5027, device='cuda:0') Validation Error: tensor(247.0895, device='cuda:0') Test Error: tensor(316.6819, device='cuda:0')
Round: 3000 Training Error: tensor(248.8822, device='cuda:0') Validation Error: tensor(248.1137, device='cuda:0') Test Error: tensor(315.9529, device='cuda:0')
Round: 3500 Training Error: tensor(247.0506, device='cuda:0') Validation Error: tensor(251.0836, device='cuda:0') Test Error: tensor(317.1518, device='cuda:0')
Round: 4000 Training Error: tensor(245.6199, device='cuda:0') Validation Error: tensor(252.0396, device='cuda:0') Test Error: tensor(316.2269, device='cuda:0')
Round: 4500 Training Error: tensor(244.1946, device='cuda:0') Validation Error: tensor(251.3516, device='cuda:0') Test Error: tensor(317.5596, device='cuda:0')
Round: 5000 Training Error: tensor(241.7529, device='cuda:0') Validation Error: tensor(252.1308, device='cuda:0') Test Error: tensor(315.2112, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'dr', 'fridge', 'hvac', 'mw']
Round: 500 Training Error: tensor(540.8162, device='cuda:0') Validation Error: tensor(494.9314, device='cuda:0') Test Error: tensor(603.0892, device='cuda:0')
Round: 1000 Training Error: tensor(421.1273, device='cuda:0') Validation Error: tensor(379.5556, device='cuda:0') Test Error: tensor(475.7214, device='cuda:0')
Round: 1500 Training Error: tensor(310.5739, device='cuda:0') Validation Error: tensor(274.8213, device='cuda:0') Test Error: tensor(364.4813, device='cuda:0')
Round: 2000 Training Error: tensor(265.1983, device='cuda:0') Validation Error: tensor(246.2594, device='cuda:0') Test Error: tensor(324.2300, device='cuda:0')
Round: 2500 Training Error: tensor(253.9635, device='cuda:0') Validation Error: tensor(251.3972, device='cuda:0') Test Error: tensor(316.3761, device='cuda:0')
Round: 3000 Training Error: tensor(250.2970, device='cuda:0') Validation Error: tensor(255.4312, device='cuda:0') Test Error: tensor(315.9387, device='cuda:0')
Round: 3500 Training Error: tensor(248.5169, device='cuda:0') Validation Error: tensor(258.7251, device='cuda:0') Test Error: tensor(316.2660, device='cuda:0')
Round: 4000 Training Error: tensor(246.9875, device='cuda:0') Validation Error: tensor(260.1533, device='cuda:0') Test Error: tensor(314.5458, device='cuda:0')
Round: 4500 Training Error: tensor(245.1566, device='cuda:0') Validation Error: tensor(259.9648, device='cuda:0') Test Error: tensor(314.5127, device='cuda:0')
Round: 5000 Training Error: tensor(242.5795, device='cuda:0') Validation Error: tensor(258.7143, device='cuda:0') Test Error: tensor(313.2657, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'dr', 'fridge', 'mw', 'hvac']
Round: 500 Training Error: tensor(540.5735, device='cuda:0') Validation Error: tensor(494.6375, device='cuda:0') Test Error: tensor(602.8580, device='cuda:0')
Round: 1000 Training Error: tensor(421.1934, device='cuda:0') Validation Error: tensor(378.6679, device='cuda:0') Test Error: tensor(474.7758, device='cuda:0')
Round: 1500 Training Error: tensor(310.3030, device='cuda:0') Validation Error: tensor(272.2061, device='cuda:0') Test Error: tensor(364.1262, device='cuda:0')
Round: 2000 Training Error: tensor(262.5471, device='cuda:0') Validation Error: tensor(244.8548, device='cuda:0') Test Error: tensor(328.3669, device='cuda:0')
Round: 2500 Training Error: tensor(252.9513, device='cuda:0') Validation Error: tensor(247.3736, device='cuda:0') Test Error: tensor(322.4531, device='cuda:0')
Round: 3000 Training Error: tensor(250.5496, device='cuda:0') Validation Error: tensor(250.5603, device='cuda:0') Test Error: tensor(322.3710, device='cuda:0')
Round: 3500 Training Error: tensor(249.1500, device='cuda:0') Validation Error: tensor(251.5350, device='cuda:0') Test Error: tensor(322.0905, device='cuda:0')
Round: 4000 Training Error: tensor(248.2574, device='cuda:0') Validation Error: tensor(253.0050, device='cuda:0') Test Error: tensor(321.6844, device='cuda:0')
Round: 4500 Training Error: tensor(246.5504, device='cuda:0') Validation Error: tensor(253.3698, device='cuda:0') Test Error: tensor(321.2380, device='cuda:0')
Round: 5000 Training Error: tensor(242.9397, device='cuda:0') Validation Error: tensor(254.7923, device='cuda:0') Test Error: tensor(316.1375, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'dr', 'mw', 'hvac', 'fridge']
Round: 500 Training Error: tensor(541.2000, device='cuda:0') Validation Error: tensor(494.7268, device='cuda:0') Test Error: tensor(603.3606, device='cuda:0')
Round: 1000 Training Error: tensor(421.4569, device='cuda:0') Validation Error: tensor(379.0273, device='cuda:0') Test Error: tensor(475.2215, device='cuda:0')
Round: 1500 Training Error: tensor(310.4303, device='cuda:0') Validation Error: tensor(280.1547, device='cuda:0') Test Error: tensor(361.8735, device='cuda:0')
Round: 2000 Training Error: tensor(264.4651, device='cuda:0') Validation Error: tensor(257.2226, device='cuda:0') Test Error: tensor(318.5247, device='cuda:0')
Round: 2500 Training Error: tensor(254.6132, device='cuda:0') Validation Error: tensor(262.9338, device='cuda:0') Test Error: tensor(311.0239, device='cuda:0')
Round: 3000 Training Error: tensor(251.2452, device='cuda:0') Validation Error: tensor(268.0677, device='cuda:0') Test Error: tensor(308.5161, device='cuda:0')
Round: 3500 Training Error: tensor(249.1796, device='cuda:0') Validation Error: tensor(267.5498, device='cuda:0') Test Error: tensor(306.7480, device='cuda:0')
Round: 4000 Training Error: tensor(247.2908, device='cuda:0') Validation Error: tensor(270.2761, device='cuda:0') Test Error: tensor(306.6015, device='cuda:0')
Round: 4500 Training Error: tensor(245.2560, device='cuda:0') Validation Error: tensor(266.9689, device='cuda:0') Test Error: tensor(306.2149, device='cuda:0')
Round: 5000 Training Error: tensor(242.7394, device='cuda:0') Validation Error: tensor(267.3508, device='cuda:0') Test Error: tensor(305.5433, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'dr', 'mw', 'fridge', 'hvac']
Round: 500 Training Error: tensor(540.4891, device='cuda:0') Validation Error: tensor(494.4224, device='cuda:0') Test Error: tensor(602.8600, device='cuda:0')
Round: 1000 Training Error: tensor(421.4471, device='cuda:0') Validation Error: tensor(379.7471, device='cuda:0') Test Error: tensor(475.2442, device='cuda:0')
Round: 1500 Training Error: tensor(310.4555, device='cuda:0') Validation Error: tensor(281.9988, device='cuda:0') Test Error: tensor(362.6397, device='cuda:0')
Round: 2000 Training Error: tensor(262.2314, device='cuda:0') Validation Error: tensor(253.9780, device='cuda:0') Test Error: tensor(321.4050, device='cuda:0')
Round: 2500 Training Error: tensor(251.6522, device='cuda:0') Validation Error: tensor(255.3272, device='cuda:0') Test Error: tensor(314.4594, device='cuda:0')
Round: 3000 Training Error: tensor(248.8734, device='cuda:0') Validation Error: tensor(259.5728, device='cuda:0') Test Error: tensor(311.1573, device='cuda:0')
Round: 3500 Training Error: tensor(247.4445, device='cuda:0') Validation Error: tensor(259.7369, device='cuda:0') Test Error: tensor(312.9294, device='cuda:0')
Round: 4000 Training Error: tensor(246.3375, device='cuda:0') Validation Error: tensor(260.6943, device='cuda:0') Test Error: tensor(313.1237, device='cuda:0')
Round: 4500 Training Error: tensor(244.8237, device='cuda:0') Validation Error: tensor(260.7637, device='cuda:0') Test Error: tensor(312.9869, device='cuda:0')
Round: 5000 Training Error: tensor(241.7354, device='cuda:0') Validation Error: tensor(260.9234, device='cuda:0') Test Error: tensor(313.0320, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'mw', 'hvac', 'fridge', 'dr']
Round: 500 Training Error: tensor(540.3943, device='cuda:0') Validation Error: tensor(494.2693, device='cuda:0') Test Error: tensor(602.9650, device='cuda:0')
Round: 1000 Training Error: tensor(420.8450, device='cuda:0') Validation Error: tensor(378.6823, device='cuda:0') Test Error: tensor(476.0047, device='cuda:0')
Round: 1500 Training Error: tensor(309.2187, device='cuda:0') Validation Error: tensor(270.8133, device='cuda:0') Test Error: tensor(364.4922, device='cuda:0')
Round: 2000 Training Error: tensor(260.9543, device='cuda:0') Validation Error: tensor(243.9134, device='cuda:0') Test Error: tensor(323.0163, device='cuda:0')
Round: 2500 Training Error: tensor(250.6159, device='cuda:0') Validation Error: tensor(248.8939, device='cuda:0') Test Error: tensor(319.5339, device='cuda:0')
Round: 3000 Training Error: tensor(247.8437, device='cuda:0') Validation Error: tensor(252.6388, device='cuda:0') Test Error: tensor(319.5296, device='cuda:0')
Round: 3500 Training Error: tensor(246.3753, device='cuda:0') Validation Error: tensor(253.8578, device='cuda:0') Test Error: tensor(319.7795, device='cuda:0')
Round: 4000 Training Error: tensor(245.1658, device='cuda:0') Validation Error: tensor(255.0155, device='cuda:0') Test Error: tensor(318.8424, device='cuda:0')
Round: 4500 Training Error: tensor(243.8972, device='cuda:0') Validation Error: tensor(255.7450, device='cuda:0') Test Error: tensor(318.1682, device='cuda:0')
Round: 5000 Training Error: tensor(242.0836, device='cuda:0') Validation Error: tensor(253.8356, device='cuda:0') Test Error: tensor(317.9909, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'mw', 'hvac', 'dr', 'fridge']
Round: 500 Training Error: tensor(540.7913, device='cuda:0') Validation Error: tensor(494.4254, device='cuda:0') Test Error: tensor(603.2006, device='cuda:0')
Round: 1000 Training Error: tensor(420.9496, device='cuda:0') Validation Error: tensor(377.7245, device='cuda:0') Test Error: tensor(475.6885, device='cuda:0')
Round: 1500 Training Error: tensor(309.5500, device='cuda:0') Validation Error: tensor(271.8246, device='cuda:0') Test Error: tensor(364.6754, device='cuda:0')
Round: 2000 Training Error: tensor(261.5846, device='cuda:0') Validation Error: tensor(244.0962, device='cuda:0') Test Error: tensor(326.3383, device='cuda:0')
Round: 2500 Training Error: tensor(252.0646, device='cuda:0') Validation Error: tensor(247.4625, device='cuda:0') Test Error: tensor(318.2328, device='cuda:0')
Round: 3000 Training Error: tensor(248.9305, device='cuda:0') Validation Error: tensor(251.4307, device='cuda:0') Test Error: tensor(315.2041, device='cuda:0')
Round: 3500 Training Error: tensor(246.8153, device='cuda:0') Validation Error: tensor(253.6094, device='cuda:0') Test Error: tensor(315.1755, device='cuda:0')
Round: 4000 Training Error: tensor(245.4165, device='cuda:0') Validation Error: tensor(255.0589, device='cuda:0') Test Error: tensor(314.0651, device='cuda:0')
Round: 4500 Training Error: tensor(243.7641, device='cuda:0') Validation Error: tensor(257.1393, device='cuda:0') Test Error: tensor(314.1906, device='cuda:0')
Round: 5000 Training Error: tensor(240.9635, device='cuda:0') Validation Error: tensor(254.1814, device='cuda:0') Test Error: tensor(313.0162, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'mw', 'fridge', 'hvac', 'dr']
Round: 500 Training Error: tensor(540.7205, device='cuda:0') Validation Error: tensor(494.5670, device='cuda:0') Test Error: tensor(602.9907, device='cuda:0')
Round: 1000 Training Error: tensor(421.0420, device='cuda:0') Validation Error: tensor(378.8973, device='cuda:0') Test Error: tensor(475.5669, device='cuda:0')
Round: 1500 Training Error: tensor(310.4538, device='cuda:0') Validation Error: tensor(272.1894, device='cuda:0') Test Error: tensor(363.9479, device='cuda:0')
Round: 2000 Training Error: tensor(263.3079, device='cuda:0') Validation Error: tensor(246.2611, device='cuda:0') Test Error: tensor(325.1268, device='cuda:0')
Round: 2500 Training Error: tensor(253.2382, device='cuda:0') Validation Error: tensor(250.2198, device='cuda:0') Test Error: tensor(320.0164, device='cuda:0')
Round: 3000 Training Error: tensor(250.5422, device='cuda:0') Validation Error: tensor(252.9008, device='cuda:0') Test Error: tensor(317.2086, device='cuda:0')
Round: 3500 Training Error: tensor(249.1164, device='cuda:0') Validation Error: tensor(255.4119, device='cuda:0') Test Error: tensor(315.5250, device='cuda:0')
Round: 4000 Training Error: tensor(247.9021, device='cuda:0') Validation Error: tensor(256.3656, device='cuda:0') Test Error: tensor(315.0076, device='cuda:0')
Round: 4500 Training Error: tensor(245.8414, device='cuda:0') Validation Error: tensor(260.6895, device='cuda:0') Test Error: tensor(315.1607, device='cuda:0')
Round: 5000 Training Error: tensor(243.2027, device='cuda:0') Validation Error: tensor(262.4325, device='cuda:0') Test Error: tensor(313.0303, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'mw', 'fridge', 'dr', 'hvac']
Round: 500 Training Error: tensor(540.5006, device='cuda:0') Validation Error: tensor(494.7674, device='cuda:0') Test Error: tensor(602.9574, device='cuda:0')
Round: 1000 Training Error: tensor(421.0035, device='cuda:0') Validation Error: tensor(378.4303, device='cuda:0') Test Error: tensor(475.0771, device='cuda:0')
Round: 1500 Training Error: tensor(309.8958, device='cuda:0') Validation Error: tensor(276.6538, device='cuda:0') Test Error: tensor(363.0382, device='cuda:0')
Round: 2000 Training Error: tensor(261.7489, device='cuda:0') Validation Error: tensor(247.8285, device='cuda:0') Test Error: tensor(322.4850, device='cuda:0')
Round: 2500 Training Error: tensor(252.0527, device='cuda:0') Validation Error: tensor(248.2882, device='cuda:0') Test Error: tensor(312.1345, device='cuda:0')
Round: 3000 Training Error: tensor(249.5249, device='cuda:0') Validation Error: tensor(251.6739, device='cuda:0') Test Error: tensor(312.0940, device='cuda:0')
Round: 3500 Training Error: tensor(248.2620, device='cuda:0') Validation Error: tensor(253.5078, device='cuda:0') Test Error: tensor(312.1366, device='cuda:0')
Round: 4000 Training Error: tensor(247.2580, device='cuda:0') Validation Error: tensor(255.3435, device='cuda:0') Test Error: tensor(311.3181, device='cuda:0')
Round: 4500 Training Error: tensor(245.3550, device='cuda:0') Validation Error: tensor(257.6432, device='cuda:0') Test Error: tensor(313.0081, device='cuda:0')
Round: 5000 Training Error: tensor(242.4116, device='cuda:0') Validation Error: tensor(258.3799, device='cuda:0') Test Error: tensor(311.9457, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'mw', 'dr', 'hvac', 'fridge']
Round: 500 Training Error: tensor(541.1887, device='cuda:0') Validation Error: tensor(494.7078, device='cuda:0') Test Error: tensor(603.3712, device='cuda:0')
Round: 1000 Training Error: tensor(421.1799, device='cuda:0') Validation Error: tensor(378.7794, device='cuda:0') Test Error: tensor(475.6468, device='cuda:0')
Round: 1500 Training Error: tensor(310.4423, device='cuda:0') Validation Error: tensor(281.7424, device='cuda:0') Test Error: tensor(362.0083, device='cuda:0')
Round: 2000 Training Error: tensor(262.4908, device='cuda:0') Validation Error: tensor(260.9486, device='cuda:0') Test Error: tensor(319.6986, device='cuda:0')
Round: 2500 Training Error: tensor(252.3148, device='cuda:0') Validation Error: tensor(267.4231, device='cuda:0') Test Error: tensor(309.8112, device='cuda:0')
Round: 3000 Training Error: tensor(249.6975, device='cuda:0') Validation Error: tensor(265.3488, device='cuda:0') Test Error: tensor(308.6835, device='cuda:0')
Round: 3500 Training Error: tensor(248.1424, device='cuda:0') Validation Error: tensor(262.7982, device='cuda:0') Test Error: tensor(307.9156, device='cuda:0')
Round: 4000 Training Error: tensor(246.7573, device='cuda:0') Validation Error: tensor(261.7027, device='cuda:0') Test Error: tensor(307.8691, device='cuda:0')
Round: 4500 Training Error: tensor(245.3032, device='cuda:0') Validation Error: tensor(260.5126, device='cuda:0') Test Error: tensor(307.3248, device='cuda:0')
Round: 5000 Training Error: tensor(243.3946, device='cuda:0') Validation Error: tensor(261.4819, device='cuda:0') Test Error: tensor(306.0464, device='cuda:0')
/zf14/yj9xs/anaconda3/lib/python3.6/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
cnn-tree-73.py:168: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_losses[t] = test_loss.data[0]
cnn-tree-73.py:169: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  valid_losses[t] = valid_loss.data[0]
cnn-tree-73.py:170: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_losses[t] = loss.data[0]
cnn-tree-73.py:182: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  print("Round:", t, "Training Error:", loss.data[0], "Validation Error:", valid_loss.data[0], "Test Error:", test_loss.data[0])
6 2 0.001 5000 0.0 ['dw', 'mw', 'dr', 'fridge', 'hvac']
Round: 500 Training Error: tensor(540.4257, device='cuda:0') Validation Error: tensor(494.6630, device='cuda:0') Test Error: tensor(603.1038, device='cuda:0')
Round: 1000 Training Error: tensor(420.7968, device='cuda:0') Validation Error: tensor(379.4183, device='cuda:0') Test Error: tensor(475.8671, device='cuda:0')
Round: 1500 Training Error: tensor(310.7018, device='cuda:0') Validation Error: tensor(274.0207, device='cuda:0') Test Error: tensor(363.1510, device='cuda:0')
Round: 2000 Training Error: tensor(263.3787, device='cuda:0') Validation Error: tensor(243.0142, device='cuda:0') Test Error: tensor(323.9561, device='cuda:0')
Round: 2500 Training Error: tensor(253.8044, device='cuda:0') Validation Error: tensor(245.7035, device='cuda:0') Test Error: tensor(314.4439, device='cuda:0')
Round: 3000 Training Error: tensor(250.9317, device='cuda:0') Validation Error: tensor(246.3723, device='cuda:0') Test Error: tensor(313.2612, device='cuda:0')
Round: 3500 Training Error: tensor(249.5448, device='cuda:0') Validation Error: tensor(247.5478, device='cuda:0') Test Error: tensor(312.5903, device='cuda:0')
Round: 4000 Training Error: tensor(248.4759, device='cuda:0') Validation Error: tensor(248.7482, device='cuda:0') Test Error: tensor(312.6197, device='cuda:0')
Round: 4500 Training Error: tensor(246.8366, device='cuda:0') Validation Error: tensor(248.7806, device='cuda:0') Test Error: tensor(312.6093, device='cuda:0')
Round: 5000 Training Error: tensor(243.6786, device='cuda:0') Validation Error: tensor(247.5991, device='cuda:0') Test Error: tensor(312.0514, device='cuda:0')
